apiVersion: v1
kind: Service
metadata:
  name: statistics-service
  namespace: asset-spy
spec:
  selector:
    app: statistics-service
  ports:
    - port: 8089
      targetPort: 8089
  type: ClusterIP